package com.gruposami.gruposamiapp.domain.servicio.model

import com.gruposami.gruposamiapp.data.database.entities.ServicioEntity
import com.gruposami.gruposamiapp.data.network.orden.model.ServicioResponse


data class Servicio(
    var id: Int,
    var descripcionPrevia: String?,
    var medido: Boolean?,
    var comentarioMedicion: String?,
    var fechaMedicion: String?,
    var montado: Boolean?,
    var comentarioMontaje: String?,
    var fechaMontaje: String?,
    var pendiente: Boolean?,
    var tipoPendiente: String?,
    var comentarioPendiente: String?,
    var fechaPendiente: String?,
    var descripcionUno: String?,
    var descripcionDos: String?,
    var descripcionTres: String?,
    var descripcionCuatro: String?,
    var descripcionCinco: String?,
    var desperfectos: String?,
    var cantidad: Int?,
    var modeloA: String?,
    var camara: String?,
    var palilleria: String?,
    var modeloB: String?,
    var luzAlto: Double?,
    var luzAncho: Double?,
    var espatulaAlto: Double?,
    var espatulaAncho: Double?,
    var ofertadaAlto: Double?,
    var ofertadaAncho: Double?,
    var formuladaAlto: Double?,
    var formuladaAncho: Double?,
    var modificadaAlto: Double?,
    var modificadaAncho: Double?,
    var sellado: String?,
    var manufacturaA: String?,
    var manufacturaB: String?,
    var observaciones: String?,
    var restos: Boolean?,
    var recogido: Boolean?,
    var fechaCreacion: String?,
    var fechaModificacion: String?,
    var estadoId: Int?,
    var ordenId: Int?,
    var faseFormulario: Int?,
)

fun ServicioResponse.toDomain() = Servicio(
    id = id,
    descripcionPrevia = descripcionPrevia,
    medido = medido,
    comentarioMedicion = comentarioMedicion,
    fechaMedicion = fechaMedicion,
//    medido_por = emptyList(),
    montado = montado,
    comentarioMontaje = comentarioMontaje,
    fechaMontaje = fechaMontaje,
//    montado_por = emptyList(),
    pendiente = pendiente,
    tipoPendiente = tipoPendiente,
    comentarioPendiente = comentarioPendiente,
    fechaPendiente = fechaPendiente,
//    pendiente_por = emptyList(),
    descripcionUno = descripcionUno,
    descripcionDos = descripcionDos,
    descripcionTres = descripcionTres,
    descripcionCuatro = descripcionCuatro,
    descripcionCinco = descripcionCinco,
    desperfectos = desperfectos,
    cantidad = cantidad,
    modeloA = modeloA,
    camara = camara,
    palilleria = palilleria,
    modeloB = modeloB,
    luzAlto = luzAlto,
    luzAncho = luzAncho,
    espatulaAlto = espatulaAlto,
    espatulaAncho = espatulaAncho,
    ofertadaAlto = ofertadaAlto,
    ofertadaAncho = ofertadaAncho,
    formuladaAlto = formuladaAlto,
    formuladaAncho = formuladaAncho,
    modificadaAlto = modificadaAlto,
    modificadaAncho = modificadaAncho,
    sellado = sellado,
    manufacturaA = manufacturaA,
    manufacturaB = manufacturaB,
    observaciones = observaciones,
    restos = restos,
    recogido = recogido,
    fechaCreacion = fechaCreacion,
    fechaModificacion = fechaModificacion,
    estadoId = estado?.id,
    ordenId = ordenId,
    faseFormulario = null
)

fun ServicioEntity.toDomain() = Servicio(
    id = id,
    descripcionPrevia = descripcionPrevia,
    medido = medido,
    comentarioMedicion = comentarioMedicion,
    fechaMedicion = fechaMedicion,
    montado = montado,
    comentarioMontaje = comentarioMontaje,
    fechaMontaje = fechaMontaje,
    pendiente = pendiente,
    tipoPendiente = tipoPendiente,
    comentarioPendiente = comentarioPendiente,
    fechaPendiente = fechaPendiente,
    descripcionUno = descripcionUno,
    descripcionDos = descripcionDos,
    descripcionTres = descripcionTres,
    descripcionCuatro = descripcionCuatro,
    descripcionCinco = descripcionCinco,
    desperfectos = desperfectos,
    cantidad = cantidad,
    modeloA = modeloA,
    camara = camara,
    palilleria = palilleria,
    modeloB = modeloB,
    luzAlto = luzAlto,
    luzAncho = luzAncho,
    espatulaAlto = espatulaAlto,
    espatulaAncho = espatulaAncho,
    ofertadaAlto = ofertadaAlto,
    ofertadaAncho = ofertadaAncho,
    formuladaAlto = formuladaAlto,
    formuladaAncho = formuladaAncho,
    modificadaAlto = modificadaAlto,
    modificadaAncho = modificadaAncho,
    sellado = sellado,
    manufacturaA = manufacturaA,
    manufacturaB = manufacturaB,
    observaciones = observaciones,
    restos = restos,
    recogido = recogido,
    fechaCreacion = fechaCreacion,
    fechaModificacion = fechaModificacion,
    estadoId = estadoId,
    ordenId = ordenId,
    faseFormulario = faseFormulario,
)